CREATE TABLE CrossCountry.[User]
(
	UserId INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	Email NVARCHAR(64) NOT NULL UNIQUE,
	UserType INT NOT NULL,
	FirstName NVARCHAR(32) NOT NULL,
	LastName NVARCHAR(32) NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);