CREATE TABLE CrossCountry.Team
(
	TeamId INT NOT NULL IDENTITY(1, 1) PRIMARY KEY,
	CoachId INT NOT NULL FOREIGN KEY
		REFERENCES CrossCountry.Coach,
	[Name] NVARCHAR(64) NOT NULL UNIQUE,
	StartYear INT NOT NULL,
	EndYear INT,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
	UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);